### PR TITLE
Update Gradle and Spring Boot

### PR DESCRIPTION
**Pull request by dacrome**

### CODE REVIEW

**Comment by dacrome** [comment]
I need to run the ITs before this PR can be merged

**Comment by tkrille** [comment]
Please apply this patch to the `application.yml`:

```
diff --git a/src/main/resources/application.yml b/src/main/resources/application.yml
index 39d36bf..abf6d6c 100644
--- a/src/main/resources/application.yml
+++ b/src/main/resources/application.yml
@@ -36,6 +36,7 @@ spring.main.banner-mode: 'off'
 spring.thymeleaf.prefix: file:${osiam.home}/templates/web/
 spring.jpa.hibernate.ddl-auto: none
 server.port: ${osiam.port:8080}
+security.oauth2.resource.filterOrder: 3
 
 management.context-path: /management
```

**Comment by tkrille** [comment]
But we still have to think about the order of the security filter chains.

**Comment by dacrome** [comment]
That is the fix, thanks @tkrille

**Pull request merged**
