### PR TITLE
fix wrong property name in install documentation

### PR DESCRIPTION
**Pull request by mirabilos**
this caused any request to fail

### CODE REVIEW

**Comment by tkrille** [comment]
Hi @mirabilos,

and thanks for your PR, good catch by the way! Could you please reword your commit message to something more obvious. There's no need to tell how this issue happened, but rather what exactly changed and why.

**Comment by mirabilos** [comment]
On Wed, 8 Jul 2015, Thomas Krille wrote:

> and thanks for your PR, good catch by the way! Could you please reword
> your commit message to something more obvious. There's no need to tell
> how this issue happened, but rather what exactly changed and why.

Sorry, ich kann nicht eine Stunde auf ein Kundenprojekt oder
Produkt buchen für eine ein-Wort-Änderung in eurer Dokumentation,
wo OSIAM nur eine kleine Randkomponente ist, die in manchen
Szenarien benötigt wird. Ich habe euch den Fix mitgeteilt,
jetzt seid ihr verantwortlich, den zu nehmen. Oder halt nicht.

Das ist so vom Bereichsleiter abgesegnet.

Gruß

## //mirabilos

tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by tkrille** [comment]
@mirabilos If you cannot adhere to the formal process to introduce your changes in OSIAM, then that's no problem at all. Just [create an issue](https://github.com/osiam/osiam/issues/new) and we'll take care of everything for you. This way everyone gets informed and we can learn from our mistakes.

**Comment by tkrille** [comment]
Thanks

**Pull request merged**
