### PR TITLE
Increase clientEntity id length to 256 characters

### PR DESCRIPTION
**Pull request by raj-subhankar**
Raised clientEntity id limit to at 256 characters. Issue #263.

### CODE REVIEW

**Comment by dacrome** [comment]
Hey @raj-subhankar 

thanks for Pull Request!
You just forgot to add a new version of a [flyway](https://flywaydb.org/) migration which should looks like [this](https://github.com/osiam/osiam/blob/master/src/main/java/db/migration/V2__migrations_from_2_5.java). The migration has to change the length of the varchar with a SQL statement.

Cheers,
David

**Comment by dacrome** [comment]
Hey @raj-subhankar,

what about my comment? Do you think you can add a new flyway migration to this PR?

Greetz,
David

**Comment by raj-subhankar** [comment]
@dacrome hey sorry for the late reply. I am sorry, I don't know how to do that.

**Comment by wallner** [comment]
Hello @raj-subhankar,
sorry for not answering earlier. I created a pull request based on yours with #278 that also adjusts all the needed database migrations. Thank you for your work!

**Pull request closed without merging**
