### PR TITLE
Change namespace for configuration properties

### LINKED ISSUE #138: Change namespace for configuration properties in YAML config?
After switching to YAML and having OSIAM_HOME in place, I wondered, whether the current namespace for configuration properties is a good choice. Currently we are using `org.osiam.*` for the ordinary properties, but there's also `osiam.home` (or `OSIAM_HOME`) for the special home directory. I really don't like special treatment of such things, so I'd suggest that we change the namespace from `org.osiam.*` to `osiam.*`. That's also more aligned with Spring Boot, because they use `spring.*` and not `org.springframework.spring-boot.*` (or whatever). I don't see any chance of a naming collision either. 

What do you think?

### PR DESCRIPTION
**Pull request by dacrome**
Resolves #138

### CODE REVIEW

**Comment by dacrome** [comment]
Corresponding IT change: https://github.com/osiam/connector4java-integration-tests/pull/328

**Comment by wallner** [comment]
Looks good, but please rebase.

**Comment by dacrome** [comment]
Rebased

**Comment by wallner** [comment]
Thank you.

**Pull request merged**
