### PR TITLE
Always return the `id` attribute

### LINKED ISSUE #151: Returning the "id" attribute is mandatory
According to the [SCIM specification](https://tools.ietf.org/html/rfc7643#section-7) the attribute "id" is required and must always be returned. At the moment we are always returning the "schemas" attribute.

### PR DESCRIPTION
**Pull request by tkrille**
The `id` attribute is defined with "a 'returned' characteristic of
always" [1].

[1] https://tools.ietf.org/html/rfc7643#section-3.1

Fixes #151

### CODE REVIEW

**Comment by wallner** [comment]
Are you adding tests too?

**Comment by tkrille** [comment]
Only if I have to :)

**Comment by tkrille** [comment]
If you tell me how, @wallner, I can do this. Unfortunately, there are no tests at all, that care about the attribute filtering when searching for resources. I really don't know how to do this with MockMVC and the current attribute filtering process. As you are the author of both, please give me some advice how to test the stuff in this PR.

**Comment by tkrille** [comment]
Alright, I've added 2 simple tests.

**Comment by wallner** [comment]
Excellent. Thank you!

**Pull request merged**
